CREATE DATABASE ORDER_MANAGEMENT
GO
USE ORDER_MANAGEMENT
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects where id = object_id(N'[dbo].[TBL_PRODUCTOS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE TBL_PRODUCTOS(
	IDPRODUCTO int IDENTITY PRIMARY KEY NOT NULL,
	CODIGO  AS ('PRO'+right('00'+CONVERT(varchar, IDPRODUCTO),(2))),
	NOMBRE varchar (30) NOT NULL,
	DESCRIPCION varchar(150),
	CANTIDAD int NULL,
	PRECIO decimal(18, 0) NULL)

END
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects where id = object_id(N'[dbo].[TBL_EMPLEADOS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE TBL_EMPLEADOS(
	IDEMPLEADO [int] IDENTITY PRIMARY KEY NOT NULL,
	CODIGO  AS ('EMP'+right('00'+CONVERT(varchar, IDEMPLEADO),(2))),
	NOMBRE nvarchar(30) NOT NULL,
	DIRECCION varchar(256) NULL,
	TELEFONO nvarchar(20) NULL,
	EMAIL nvarchar(100) NULL)

END
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects where id = object_id(N'[dbo].[TBL_ORDENES]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE TBL_ORDENES(
	IDORDEN int IDENTITY PRIMARY KEY NOT NULL,
	CODIGO  AS ('ORD'+right('00'+CONVERT(varchar, IDORDEN),(2))),
	FECHAORDEN datetime)

END
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects where id = object_id(N'[dbo].[TBL_ORDENES_DETALLE]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE TBL_ORDENES_DETALLE(
     ID int IDENTITY PRIMARY KEY,
	 IDORDEN int,
	 IDPRODUCTO int,
	 PRECIO decimal(18, 0),
	 CANTIDAD INT)

END
GO

IF NOT EXISTS (SELECT * FROM dbo.sysobjects where id = object_id(N'[dbo].[TBL_ASIGNACIONES]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE TBL_ASIGNACIONES(
     IDASIGNACION int IDENTITY PRIMARY KEY,
	 CODIGO  AS ('ASG'+right('00'+CONVERT(varchar, IDASIGNACION),(2))),
	 IDORDEN int,
	 IDEMPLEADO int,
	 FECHA datetime)

END
GO